import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import PDFDocument from "pdfkit";
import path from "path";
import QRCode from "qrcode";

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const enrollment = await prisma.enrollment.findUnique({
      where: { id: parseInt(params.id) },
    });

    if (!enrollment) {
      return NextResponse.json(
        { error: "Enrollment not found" },
        { status: 404 }
      );
    }

    const pdfBuffer = await generateEnrollmentPDF(enrollment);
    const body = new Uint8Array(pdfBuffer);

    return new Response(body, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="enrollment-${enrollment.id}.pdf"`,
      },
    });
  } catch (error) {
    console.error("Download error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

async function generateEnrollmentPDF(enrollment: any): Promise<Buffer> {
  return new Promise(async (resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // 📁 Paths (VERY IMPORTANT)
    const fontPath = path.join(
      process.cwd(),
      "public/fonts/Roboto-Regular.ttf"
    );
    const logoPath = path.join(process.cwd(), "public/logo.png");

    // ✅ Use custom font (fixes Vercel error)
    doc.font(fontPath);

    // 🔗 Generate QR Code
    const baseUrl =
      process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";

    const verificationUrl = `${baseUrl}/verify/${enrollment.id}`;
    const qrImage = await QRCode.toBuffer(verificationUrl);

    const headerColor = "#1e40af";
    const textColor = "#333";

    // ================= HEADER =================
    doc.image(logoPath, 50, 40, { width: 60 });

    doc
      .fontSize(20)
      .fillColor(headerColor)
      .text("EDUMANAGE", 120, 50);

    doc
      .fontSize(12)
      .fillColor("#666")
      .text("Enrollment Application Form", 120, 75);

    doc.moveDown(2);

    doc
      .strokeColor(headerColor)
      .lineWidth(2)
      .moveTo(50, doc.y)
      .lineTo(doc.page.width - 50, doc.y)
      .stroke();

    doc.moveDown(1.5);

    const enrollmentDate = new Date(
      enrollment.createdAt
    ).toLocaleDateString();

    // ================= STATUS =================
    sectionTitle(doc, "Application Status");

    doc.fillColor(textColor).fontSize(11);
    doc.text(`Status: ${enrollment.status}`);
    doc.text(`Applied On: ${enrollmentDate}`);
    doc.moveDown(1);

    // ================= MATRICLE =================
    if (enrollment.matricle) {
      doc.rect(50, doc.y, doc.page.width - 100, 70).stroke("#0284c7");

      doc
        .fontSize(10)
        .fillColor("#666")
        .text("STUDENT MATRICLE", 60, doc.y + 10);

      doc
        .fontSize(22)
        .fillColor("#0284c7")
        .text(enrollment.matricle, 60, doc.y + 25, {
          align: "center",
        });

      doc.moveDown(4);
    }

    // ================= PERSONAL INFO =================
    sectionTitle(doc, "Personal Information");

    doc.fillColor(textColor).fontSize(11);
    doc.text(`First Name: ${enrollment.firstName}`);
    doc.text(`Last Name: ${enrollment.lastName}`);
    doc.text(`Email: ${enrollment.email}`);
    doc.text(`Phone: ${enrollment.phone}`);
    doc.moveDown(1);

    // ================= PROGRAM =================
    sectionTitle(doc, "Program Information");

    doc.text(`Program: ${enrollment.program}`);
    doc.moveDown(1);

    // ================= QR CODE =================
    sectionTitle(doc, "Verification");

    doc.text("Scan to verify this enrollment:");
    doc.image(qrImage, doc.page.width - 150, doc.y - 20, {
      width: 100,
    });

    doc.moveDown(4);

    // ================= SIGNATURES =================
    doc.moveDown(2);

    const y = doc.y;

    doc.moveTo(60, y).lineTo(200, y).stroke();
    doc.moveTo(300, y).lineTo(440, y).stroke();

    doc.text("CEO Signature", 60, y + 5);
    doc.text("Course Instructor", 300, y + 5);

    // ================= FOOTER =================
    doc.moveDown(3);

    doc
      .fontSize(9)
      .fillColor("#666")
      .text(
        "Official document generated by EduManage System",
        50,
        doc.y,
        { align: "center" }
      );

    doc.text(
      "Generated on: " + new Date().toLocaleString(),
      { align: "center" }
    );

    doc.end();
  });
}

// ================= HELPER =================
function sectionTitle(doc: any, title: string) {
  doc.rect(50, doc.y, doc.page.width - 100, 20).fill("#1e40af");

  doc.fillColor("white").fontSize(12).text(title, 60, doc.y - 15);

  doc.moveDown(1.5);
}
